# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 568)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(256, 256))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(5, 40, 778, 461))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_1 = QtWidgets.QLabel(self.tab)
        self.label_1.setGeometry(QtCore.QRect(10, 10, 70, 21))
        self.label_1.setObjectName("label_1")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_1.setEnabled(True)
        self.lineEdit_1.setGeometry(QtCore.QRect(60, 10, 701, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_1.setAcceptDrops(True)
        self.lineEdit_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_1.setText("")
        self.lineEdit_1.setMaxLength(100)
        self.lineEdit_1.setFrame(True)
        self.lineEdit_1.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_1.setCursorPosition(0)
        self.lineEdit_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_1.setDragEnabled(False)
        self.lineEdit_1.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_1.setClearButtonEnabled(False)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 10, 321, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_3.setAcceptDrops(True)
        self.lineEdit_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setMaxLength(100)
        self.lineEdit_3.setFrame(True)
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_3.setCursorPosition(0)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setDragEnabled(False)
        self.lineEdit_3.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_3.setClearButtonEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 70, 21))
        self.label_3.setObjectName("label_3")
        self.btn_sear = QtWidgets.QPushButton(self.tab_3)
        self.btn_sear.setEnabled(True)
        self.btn_sear.setGeometry(QtCore.QRect(410, 9, 110, 24))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.btn_sear.setFont(font)
        self.btn_sear.setIconSize(QtCore.QSize(128, 128))
        self.btn_sear.setFlat(False)
        self.btn_sear.setObjectName("btn_sear")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(534, 5, 231, 419))
        self.groupBox.setObjectName("groupBox")
        self.check_box_01 = QtWidgets.QCheckBox(self.groupBox)
        self.check_box_01.setGeometry(QtCore.QRect(10, 60, 161, 17))
        self.check_box_01.setChecked(False)
        self.check_box_01.setObjectName("check_box_01")
        self.spin_number_01 = QtWidgets.QSpinBox(self.groupBox)
        self.spin_number_01.setGeometry(QtCore.QRect(10, 20, 131, 22))
        self.spin_number_01.setReadOnly(False)
        self.spin_number_01.setMaximum(100000)
        self.spin_number_01.setSingleStep(1000)
        self.spin_number_01.setProperty("value", 1000)
        self.spin_number_01.setObjectName("spin_number_01")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(150, 20, 81, 21))
        self.label_4.setObjectName("label_4")
        self.check_box_02 = QtWidgets.QCheckBox(self.groupBox)
        self.check_box_02.setGeometry(QtCore.QRect(10, 90, 161, 17))
        self.check_box_02.setObjectName("check_box_02")
        self.spin_number_02 = QtWidgets.QSpinBox(self.groupBox)
        self.spin_number_02.setGeometry(QtCore.QRect(50, 190, 61, 22))
        self.spin_number_02.setMaximum(1000)
        self.spin_number_02.setSingleStep(1)
        self.spin_number_02.setProperty("value", 14)
        self.spin_number_02.setObjectName("spin_number_02")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 190, 31, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(130, 190, 31, 21))
        self.label_7.setObjectName("label_7")
        self.spin_number_03 = QtWidgets.QSpinBox(self.groupBox)
        self.spin_number_03.setGeometry(QtCore.QRect(160, 190, 61, 22))
        self.spin_number_03.setMaximum(1000)
        self.spin_number_03.setSingleStep(1)
        self.spin_number_03.setProperty("value", 80)
        self.spin_number_03.setObjectName("spin_number_03")
        self.check_box_03 = QtWidgets.QCheckBox(self.groupBox)
        self.check_box_03.setGeometry(QtCore.QRect(10, 150, 161, 17))
        self.check_box_03.setObjectName("check_box_03")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(10, 120, 211, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 81, 21))
        self.label_5.setObjectName("label_5")
        self.radio_01 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_01.setGeometry(QtCore.QRect(20, 260, 82, 17))
        self.radio_01.setObjectName("radio_01")
        self.radio_02 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_02.setGeometry(QtCore.QRect(20, 290, 82, 17))
        self.radio_02.setObjectName("radio_02")
        self.radio_03 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_03.setGeometry(QtCore.QRect(20, 320, 82, 17))
        self.radio_03.setChecked(True)
        self.radio_03.setObjectName("radio_03")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 511, 382))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(19)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(95)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget.verticalHeader().setMinimumSectionSize(20)
        self.groupBox.raise_()
        self.lineEdit_3.raise_()
        self.label_3.raise_()
        self.btn_sear.raise_()
        self.tableWidget.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.txtMessage = QtWidgets.QTextEdit(self.tab_2)
        self.txtMessage.setGeometry(QtCore.QRect(10, 60, 481, 101))
        self.txtMessage.setObjectName("txtMessage")
        self.btn_send = QtWidgets.QPushButton(self.tab_2)
        self.btn_send.setEnabled(True)
        self.btn_send.setGeometry(QtCore.QRect(10, 180, 481, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.btn_send.setFont(font)
        self.btn_send.setIconSize(QtCore.QSize(128, 128))
        self.btn_send.setFlat(False)
        self.btn_send.setObjectName("btn_send")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 20, 391, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_2.setAcceptDrops(True)
        self.lineEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setMaxLength(100)
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setCursorPosition(0)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setDragEnabled(False)
        self.lineEdit_2.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_channel = QtWidgets.QLabel(self.centralwidget)
        self.label_channel.setGeometry(QtCore.QRect(10, 10, 771, 16))
        self.label_channel.setText("")
        self.label_channel.setOpenExternalLinks(True)
        self.label_channel.setObjectName("label_channel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Group Hunter Professional Edition 10.07"))
        self.label_1.setText(_translate("MainWindow", " Токен"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Авторизация"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "200727834"))
        self.label_3.setText(_translate("MainWindow", "Сообщество"))
        self.btn_sear.setText(_translate("MainWindow", "Поиск"))
        self.groupBox.setTitle(_translate("MainWindow", "Настройки поиска"))
        self.check_box_01.setText(_translate("MainWindow", " Открытые сообщения"))
        self.label_4.setText(_translate("MainWindow", " Количество"))
        self.check_box_02.setText(_translate("MainWindow", "Сейчас на сайте"))
        self.label_6.setText(_translate("MainWindow", " От"))
        self.label_7.setText(_translate("MainWindow", "До"))
        self.check_box_03.setText(_translate("MainWindow", "Включить возраст"))
        self.label_5.setText(_translate("MainWindow", " Пол"))
        self.radio_01.setText(_translate("MainWindow", "Мужской"))
        self.radio_02.setText(_translate("MainWindow", "Женский"))
        self.radio_03.setText(_translate("MainWindow", "Любой"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "19"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Номер"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Фамилия"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Онлайн"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Сообщения"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Сообщества"))
        self.btn_send.setText(_translate("MainWindow", "Отправить сообщение"))
        self.label_2.setText(_translate("MainWindow", " Пользователь"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Сообщения"))
